Tutorial mechanics
robotopia-x/robotopia pull request #31
Opened 2017-01-05 10:08 UTC by timgrossmann

#### Tutorial Mechanics needed for [Tutorial Design](https://github.com/hdm-project/todo/issues/30)

The state of every tutorial level will be defined in a separate file with the following syntax:
```javascript
module.exports = {
  state: {
    tiles: [
      [1, 0, 1, 1, 1, 0, 1],
      [1, 0, 1, 0, 1, 0, 1],
      [1, 0, 1, 0, 1, 0, 1],
      [1, 0, 1, 0, 1, 0, 1],
      [1, 0, 1, 0, 1, 0, 1],
      [1, 0, 1, 0, 1, 0, 1],
      [1, 0, 1, 0, 1, 0, 1],
      [1, 0, 1, 0, 1, 0, 1],
      [1, 1, 1, 0, 1, 1, 1]
    ],

    stepProgress: 0,

    entities: [
      entities.base({x: 2, y: 5, id: 'BASE'}),
      entities.robot({x: 2, y: 5, id: 'ROBOT'}),
      entities.gem({x: 0, y: 0})
    ]
  },

  goals: [
    {
      type: 'moveTo',
      params: { position: { x: 0, y: 6 }, entity: 'ROBOT' },
      desc: 'Move the Robot into the goal'
    },
    {
      type: 'collectResource',
      params: {},
      desc: 'Collect 3 Gems'
    }
  ],

  storyModal: {
    text: 'Once upon a time, there was a small robot who died... The end',
    img: '../assets/img/tutorials/tutorial1.png'
  },

  workspace: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="rotate" id="bizsM0~3M?%9v:^sintR" x="235" y="155"><field name="Direction">LEFT</field></block></xml>',

  toolbox: `<xml id="toolbox" style="display: none">
                <category name="Logic" colour="100">
                  <block type="controls_repeat_ext"></block>
                  <block type="math_number"></block>
                </category>
           </xml>`
}
```
For every tutorial you can set:
- game state
- goals (what conditions have to be met, the text which will be displayed as goals)
- storyModal text and image
- workspace and the toolbox

---

###### What to test:

- [ ] tutorial is served at http://localhost:9966/#tutorial
- [ ] at the start a level of every level (but the first) a storyModal is displayed with an image
- [ ] you can click "Start Tutorial" to make the modal disappear and code
- [ ] you see goals displayed in the upper right corner
- [ ] once you reach the goal (for level 2 it's move to x:0 y: 6) a winning dialog is displayed
- [ ] you can get to the next level by clicking "Next Level"
- [ ] the toolbox changes in every level
- [ ] the workspace changes at every level
- [ ] the game changes at every level

2017-01-05 11:19 UTC, paulsonnentag commented
Todo:
- [ ] fix tutorial complete dialog on inital load
- [ ] jump from last tutorial to real game

2017-01-05 11:47 UTC, paulsonnentag requested changes

2017-01-05 11:47 UTC, paulsonnentag commented on elements/blockly.js
> +    if (prev && _state.level.level !== prev.level.level) {
Todo comment: blockly shouldn't need to know about levels

2017-01-05 11:47 UTC, paulsonnentag commented on elements/blockly.js
> +    setInterval(saveWorkspaceFromDom, 1000)
clear Interval onunload

2017-01-05 11:47 UTC, paulsonnentag commented on elements/winningCondition.js
> +    send('stopSimulation')
we shouldn't call send here because rerendering a component shouldn't have a side effect

2017-01-05 11:47 UTC, paulsonnentag commented on elements/winningCondition.js
> +const winningCondition = (state, send) => {
I think this component should be split up in two separate components:  goal progress display and dialog

2017-01-05 11:47 UTC, paulsonnentag commented on elements/winningCondition.js
> +  return _.reduce(goals, (goal, value) => {
you can just use _.map instead

2017-01-05 11:47 UTC, paulsonnentag commented on models/game/tutorials/tutorial-1-state.js
> +    stepProgress: 0,
you can remove this, step progress is now stored in the clock model

2017-01-05 11:47 UTC, paulsonnentag commented on models/game/tutorials/initial-state.js
> +
you can remove this, step progress is now stored in the clock model

2017-01-05 11:47 UTC, paulsonnentag commented on models/game/tutorials/tutorial-2-state.js
> +    stepProgress: 0,
same as above

2017-01-05 11:47 UTC, paulsonnentag commented on models/level.js
> +      send('level:_setDisplayStoryModal', { displayStory: false }, _.noop)
Is there a reason to split up closeStoryModal in effect and reducer?

2017-01-06 15:51 UTC, paulsonnentag commented
You can merge it like it is if you want or split up the components your call.

2017-01-07 07:58 UTC, timgrossmann commented
I think I'll give splitting the components a try today, if i can't find enough time, i'll merge it like this and split it up later.

2017-01-07 15:25 UTC, paulsonnentag approved these changes

2017-01-07 15:27 UTC, paulsonnentag commented
![](http://i.giphy.com/9PyhoXey73EpW.gif)

2017-01-07 15:27 UTC, merged