Restructure tutorial
robotopia-x/robotopia pull request #87
Opened 2017-02-17 11:23 UTC by timgrossmann

## Restructure tutorial
> Solves Issue #67 

- removed the old tutorials (3-6)
- added Instruction panel to the tutorial levels
- modified the story dialog to only display goals and story
- added unlocked block to win dialog
- switched the direction to make it work with the right blocks

- added more tutorial parameters
  - instructions (img and text)
  - unlocked block in story modal (img and text)

> Should be ready to implement new improved tutorials now

#### Please test before approving and merging! The direction change should work, but there could be edge cases I missed

###### It's probably smart to wait until after the user test this weekend to merge it

2017-02-18 11:27 UTC, H3rby7 commented on pages/tutorial.js
>    })
Could you add a button to quickly hide/show the new panel with the instructions and the goal? (kind of like a slide-in/hamburger menu). As of state now the view feels really squished into the browser with 3 panels active.  
Yes I know they are resizable and the player can simply resize it out, but i really think the instruction part should be a slide-in. (Maybe upon hovering over the slide-in button we could display the goals again without opening the slide-in)  

![image](https://cloud.githubusercontent.com/assets/5808849/23092905/44625eec-f5d5-11e6-92a2-9b6269d0a6a0.png)

2017-02-18 11:29 UTC, H3rby7 requested changes
Could you take a look at the comment for the instruction view?

2017-02-18 12:17 UTC, paulsonnentag commented on pages/tutorial.js
>    })
I agree with @H3rby7. I think the image is redundant. If you don't want to loose the arrows you could add them as entities into the actual game world.


What do you think about something like this. I know mad gimp skillz
![44625eec-f5d5-11e6-92a2-9b6269d0a6a0 1](https://cloud.githubusercontent.com/assets/650540/23093162/ac343170-f5db-11e6-971f-e8f825d88d6f.png)

You could actually modify the page layout, so you can set the initial size of the panels. Something like this:

``` Javascript
  const panelGroupHtml = panelGroup.component(...context)(id, {
    props: {
      panelViews: panels
    }
    initialState: {
      panelSizes: [1, 2, 2]
    }
  })
```

in [pageLayout](https://github.com/robotopia-x/robotopia/blob/ad41215a5b473ecde0aad0b851cba558c21663bb/elements/page-layout.js#L20)

2017-02-19 10:27 UTC, timgrossmann commented
👍 Will take care of it tomorrow

2017-02-20 13:58 UTC, timgrossmann commented on pages/tutorial.js
>    })
That looks like a nice idea! 
You should add that to the component, I seriously hardly understand something in the panel-group file. (also there is very few documentation besides the default behaviour of that module)

I adjusted the instruction panel to look like you suggested.

2017-02-20 15:35 UTC, timgrossmann commented
I don't know why, but the toolbox is always empty since rebasing it on develop.

2017-02-20 23:10 UTC, paulsonnentag commented
The resize doesn't work yet, I'll fix it tomorrow

2017-02-20 23:10 UTC, merged